name: git_stamp_example
publish_to: "none"
homepage: https://aroncode.com
repository: https://github.com/arononak/git_stamp
environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  url_launcher: ^6.2.3
  flutter:
    sdk: flutter
dev_dependencies:
  git_stamp:
    path: ../
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true