name: example
version: 1.0.0+1
publish_to: "none"
homepage: https://aroncode.com
repository: https://github.com/arononak/git_stamp
environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  aron_gradient_line: ^1.0.1
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
dev_dependencies:
  git_stamp:
    path: ../
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.25.2
flutter:
  uses-material-design: true