name: example
publish_to: "none"
homepage: https://aroncode.com
repository: https://github.com/arononak/git_stamp
environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  git_stamp:
    git:
      url: https://github.com/arononak/git_stamp
      ref: c6d50253b1b640bb68ca8a1002fabf8e1f886e61
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true