name: example
publish_to: "none"
homepage: https://aroncode.com
repository: https://github.com/arononak/git_stamp
environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  git_stamp:
    git:
      url: https://github.com/arononak/git_stamp
      ref: ea12d1a95acd74585c3300e4c7ef6e02e66db91f
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true