name: git_stamp
description: "Provides information about the project's Git repository and more. From simple information such as build-branch to a screen with Flutter code with commits and change history."
version: 3.1.0
homepage: https://aroncode.com
repository: https://github.com/arononak/git_stamp
issue_tracker: https://github.com/arononak/git_stamp/issues
documentation: https://arononak.github.io/git_stamp/doc/api/index.html
license: MIT

topics:
 - git
 - git-history
 - git-integration
 - tool
 - codegen

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.5.0
  intl: ^0.19.0
  pubspec_parse: ^1.3.0
  pub_semver: ^2.1.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
