name: dev

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Install make on Windows
        if: runner.os == 'Windows'
        run: choco install -y make sed
      - run: flutter --version
      - run: flutter pub get
      - run: make -C example tests
  generate_screenshots:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
      - run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: git config --global user.name 'github-actions[bot]'
      - run: git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: flutter pub get
      - run: make -C example sync
      - run: make -C example screenshots
      - run: |
          git add list.png icon.png files.png details.png
          git commit -m 'Screenshot update'
          git push origin HEAD:main
  build:
    runs-on: ubuntu-latest
    needs: generate_screenshots
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git log --oneline
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'
      - run: flutter --version
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - run: flutter pub get
      - run: git config --global user.name 'github-actions[bot]'
      - run: git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: make -C example build
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: example/build/web
  firebase_deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: build
          path: example/build/web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITSTAMP }}"
          projectId: gitstamp
          channelId: live
          entryPoint: ./example
