name: Generate Dart Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart doc
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'DOC Update'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}