name: prod

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  format_code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          dart format bin
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m 'Code update'
            git push origin HEAD:main
          fi
  generate_doc:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: format_code
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          flutter pub get
          dart doc
          git add doc
          if ! git diff-index --quiet HEAD; then
            git commit -m 'DOC update'
            git push origin HEAD:main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: generate_doc
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'
      - run: flutter pub get
      - run: dart format .
      - run: dart doc
      - run: dart pub publish --force
