name: tests

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  tests_and_generate_screenshots:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - run: flutter --version
      - run: flutter pub get
      - run: make -C example tests
      - run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
      - run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - uses: actions/setup-node@v3
        with:
          node-version: '16' 
      - run: make -C example sync
      - run: make -C example screenshots
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add list.png icon.png files.png details.png
          git commit -m 'Screenshot update'
          git push origin HEAD:main
