name: tests

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - run: flutter --version
      - run: flutter pub get
      - run: make -C example integration_tests
